### ISSUE TITLE
Missing ws transport

### ISSUE THREAD

**Issue by robinzimmermann** [kaazing/gateway.client.java#9]
I'm testing the Java client library using [tools.wscat](https://github.com/kaazing/tools.wscat). I get the error below.

It looks like when this repo is build, the resulting client jar file is missing the `transport` directory in `org.kaazing.gateway.client`. This means the `ws` and `http` transports are missing.

``` java
Exception in thread "main" java.lang.NoClassDefFoundError: org/kaazing/gateway/client/transport/ws/WebSocketDelegate
    at org.kaazing.gateway.client.impl.ws.WebSocketTransportHandler.processConnect(WebSocketTransportHandler.java:72)
    at org.kaazing.gateway.client.impl.wsn.WebSocketNativeBalancingHandler.processConnect(WebSocketNativeBalancingHandler.java:69)
    at org.kaazing.gateway.client.impl.wsn.WebSocketNativeHandshakeHandler.processConnect(WebSocketNativeHandshakeHandler.java:89)
    at org.kaazing.gateway.client.impl.WebSocketHandlerAdapter.processConnect(WebSocketHandlerAdapter.java:37)
    at org.kaazing.gateway.client.impl.wsn.WebSocketNativeHandler.processConnect(WebSocketNativeHandler.java:138)
    at org.kaazing.gateway.client.impl.ws.WebSocketSelectedHandlerImpl.processConnect(WebSocketSelectedHandlerImpl.java:79)
    at org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandler.initDelegate(WebSocketCompositeHandler.java:223)
    at org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandler.fallbackNext(WebSocketCompositeHandler.java:203)
    at org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandler.processConnect(WebSocketCompositeHandler.java:187)
    at org.kaazing.net.ws.impl.WebSocketImpl.connect(WebSocketImpl.java:341)
    at org.kaazing.tools.WSCat.main(WSCat.java:53)
Caused by: java.lang.ClassNotFoundException: org.kaazing.gateway.client.transport.ws.WebSocketDelegate
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 11 more
```

**Comment by dpwspoon** [comment]
This is a bug in tools.wscat not gateway.client.java.  I've fixed tools.wscat

**Comment by robinzimmermann** [comment]
I just tested this and it works, thank!
